### PR TITLE
bugfix: were no delays between retries when forever=true and retries=null

### PR DESCRIPTION
**Pull request by m59peacemaker**

### CODE REVIEW

**Comment by m59peacemaker** [comment]
Fixes https://github.com/tim-kos/node-retry/issues/32. When no `retries` were given, the `timeouts` array was empty, so there was no delay. I simply added a check for the forever option and an empty `timeout` array, and if so, created and push a timeout. My new test and all tests pass.

**Comment by tim-kos** [comment]
I am not sure what the point is of setting retries: null. You should just set forever: true and let the default values for retries, minTimeout, maxTimeout and factor take care of everything for you. With forever: true it will step through the timeouts array and once that is done with it starts anew.

Since this is a rare edge case and confuses people who set retries to `null` I will still merge this. Thank you for the work. :)

**Comment by m59peacemaker** [comment]
Oh, that makes sense. I'd say it needs to pass this test anyway, but the implementation could have been to set `retries` to the default if it is falsey.

**Comment by tim-kos** [comment]
Nah, if someone overwrites the default value for `retries` with something `false`y, then they should know what they are doing. Retries is an integer, so overwriting it with `null` or `false` doesn't make sense.

I think what would make sense is to instead of setting `forever` to `true`, one should be able to set `retries` to `"forever"`.

I have updated the readme to express that `forever: true` means the timeouts array generated from retries, minTimeout and maxTimeout will be restarted once its last timeout was used.

That should be good enough and is also intuitive. Anyways, I have merged this already. :)

**Pull request merged**
