### PR TITLE
Add Typescript support

### PR DESCRIPTION
**Pull request by itsJess1ca**
I believe I covered the majority of the API but this should be a good start in providing typescript support

### CODE REVIEW

**Comment by zixia** [comment]
:+1:

**Comment by tim-kos** [comment]
There is one conflict. Once fixed, I am happy to merge this.

**Comment by j3ddesign** [comment]
That should cover that, haven't checked here in a while, sorry about that.

**Comment by tim-kos** [comment]
Hm GitHub still reports a conflicted package.json. Did you merge master from upstream?

**Comment by j3ddesign** [comment]
My bad - wasn't paying much attention last time :P All good now.

**Review by tim-kos — CHANGES_REQUESTED** [review]
Nice work!

You are removing some functions from retry_operation unintentionally (like _maxRetry and reset). Possible a merge problem? Can you please account for that? Then I am happy to merge.

**Comment by tim-kos** [comment]
Closing then in favor of the ts definitions here https://www.npmjs.com/package/@types/retry

**Pull request closed without merging**
