### PR TITLE
Added a simple implementation of the stop() method for issue #17

### PR DESCRIPTION
**Pull request by maxnachlinger**

### CODE REVIEW

**Comment by maxnachlinger** [comment]
If this change looks fine, I'll also be happy to create a simple example js file showing how to use ``stop()``.

**Comment by tim-kos** [comment]
Looks good to me. Please add an example. :+1:

**Comment by kadishmal** [comment]
:+1:

**Comment by maxnachlinger** [comment]
Added ``example/stop.js``, hopefully it's clear enough.

**Comment by maxnachlinger** [comment]
Do you guys need me to add any additional examples?

**Comment by harr999y** [comment]
Nice work, thanks. :+1: 
And when can it publish to NPM?
Waiting for this. :)

**Comment by cludden** [comment]
Any way this can get merged/published?

**Comment by m59peacemaker** [comment]
@maxnachlinger I would publish your fork on npm under your namespace at least since it isn't be merged here.

**Comment by tim-kos** [comment]
Hey @maxnachlinger,

Sorry for not getting back to you earlier. I am going to merge this tomorrow. Unfortunately, there are conflicts now, which need to be resolved. If you have some time, please resolve them. Otherwise I will do it and mention your name in the commit message.

**Comment by maxnachlinger** [comment]
Hey @tim-kos,
Conflicts resolved, thanks for this awesome library.

**Comment by tim-kos** [comment]
Thank you.

I have added a fix to this so that it works as expected with forever: true. Pushed a release to npm.

**Pull request merged**
